#!/usr/bin/env python

DUPLICATION_CHECK = "匹配"
DEPARTMENT = "应聘部门"
MOBILE = "手机"
NAME = "姓名"
SEX = "性别"
DEGREE = "学历"
MAJOR = "专业"
UNIVERSITY = "学校"
TARGETED_POSITION = "应聘职位"
EMAIL = "EMAIL"
RESUME = "简历来源"
RESERVED_SLOT = "预约面试时间"
LOCATION = "预约面试地点\n北京/杭州/合肥"
ADDEDDATE = "记录时间"
CONTACT = "联系人"
INVITEMAIL = "邀请邮件"
REFUSEMAIL = "拒绝邮件"

MARKED = "Y"