# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Device_pb2 as Device__pb2
import grpc_service_pb2 as grpc__service__pb2


class DeviceServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetJsonDeviceBase = channel.unary_unary(
        '/device.DeviceService/GetJsonDeviceBase',
        request_serializer=Device__pb2.DeviceBase.SerializeToString,
        response_deserializer=grpc__service__pb2.GetJsonReply.FromString,
        )
    self.GetJsonDevicePhysicalEntities = channel.unary_unary(
        '/device.DeviceService/GetJsonDevicePhysicalEntities',
        request_serializer=Device__pb2.DevicePhysicalEntities.SerializeToString,
        response_deserializer=grpc__service__pb2.GetJsonReply.FromString,
        )


class DeviceServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetJsonDeviceBase(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJsonDevicePhysicalEntities(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetJsonDeviceBase': grpc.unary_unary_rpc_method_handler(
          servicer.GetJsonDeviceBase,
          request_deserializer=Device__pb2.DeviceBase.FromString,
          response_serializer=grpc__service__pb2.GetJsonReply.SerializeToString,
      ),
      'GetJsonDevicePhysicalEntities': grpc.unary_unary_rpc_method_handler(
          servicer.GetJsonDevicePhysicalEntities,
          request_deserializer=Device__pb2.DevicePhysicalEntities.FromString,
          response_serializer=grpc__service__pb2.GetJsonReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'device.DeviceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
