# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Device.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import grpc_service_pb2 as grpc__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Device.proto',
  package='device',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x44\x65vice.proto\x12\x06\x64\x65vice\x1a\x12grpc_service.proto\"s\n\nDeviceBase\x12\x10\n\x08HostName\x18\x01 \x01(\t\x12\x0f\n\x07HostOid\x18\x02 \x01(\t\x12\x15\n\rMaxChassisNum\x18\x03 \x01(\r\x12\x12\n\nMaxSlotNum\x18\x04 \x01(\r\x12\x17\n\x0fHostDescription\x18\x05 \x01(\t\"\xd4\x01\n\x16\x44\x65vicePhysicalEntities\x12\x35\n\x06\x65ntity\x18\x01 \x03(\x0b\x32%.device.DevicePhysicalEntities.Entity\x1a\x82\x01\n\x06\x45ntity\x12\x15\n\rPhysicalIndex\x18\x01 \x01(\r\x12\x12\n\nVendorType\x18\x02 \x01(\t\x12\x13\n\x0b\x45ntityClass\x18\x03 \x01(\r\x12\x13\n\x0bSoftwareRev\x18\x04 \x01(\t\x12\x14\n\x0cSerialNumber\x18\x05 \x01(\t\x12\r\n\x05Model\x18\x06 \x01(\t2\xb5\x01\n\rDeviceService\x12\x45\n\x11GetJsonDeviceBase\x12\x12.device.DeviceBase\x1a\x1a.grpc_service.GetJsonReply\"\x00\x12]\n\x1dGetJsonDevicePhysicalEntities\x12\x1e.device.DevicePhysicalEntities\x1a\x1a.grpc_service.GetJsonReply\"\x00')
  ,
  dependencies=[grpc__service__pb2.DESCRIPTOR,])




_DEVICEBASE = _descriptor.Descriptor(
  name='DeviceBase',
  full_name='device.DeviceBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='HostName', full_name='device.DeviceBase.HostName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HostOid', full_name='device.DeviceBase.HostOid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaxChassisNum', full_name='device.DeviceBase.MaxChassisNum', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaxSlotNum', full_name='device.DeviceBase.MaxSlotNum', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HostDescription', full_name='device.DeviceBase.HostDescription', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=159,
)


_DEVICEPHYSICALENTITIES_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='device.DevicePhysicalEntities.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PhysicalIndex', full_name='device.DevicePhysicalEntities.Entity.PhysicalIndex', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VendorType', full_name='device.DevicePhysicalEntities.Entity.VendorType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EntityClass', full_name='device.DevicePhysicalEntities.Entity.EntityClass', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SoftwareRev', full_name='device.DevicePhysicalEntities.Entity.SoftwareRev', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SerialNumber', full_name='device.DevicePhysicalEntities.Entity.SerialNumber', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Model', full_name='device.DevicePhysicalEntities.Entity.Model', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=374,
)

_DEVICEPHYSICALENTITIES = _descriptor.Descriptor(
  name='DevicePhysicalEntities',
  full_name='device.DevicePhysicalEntities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='device.DevicePhysicalEntities.entity', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DEVICEPHYSICALENTITIES_ENTITY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=374,
)

_DEVICEPHYSICALENTITIES_ENTITY.containing_type = _DEVICEPHYSICALENTITIES
_DEVICEPHYSICALENTITIES.fields_by_name['entity'].message_type = _DEVICEPHYSICALENTITIES_ENTITY
DESCRIPTOR.message_types_by_name['DeviceBase'] = _DEVICEBASE
DESCRIPTOR.message_types_by_name['DevicePhysicalEntities'] = _DEVICEPHYSICALENTITIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceBase = _reflection.GeneratedProtocolMessageType('DeviceBase', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEBASE,
  __module__ = 'Device_pb2'
  # @@protoc_insertion_point(class_scope:device.DeviceBase)
  ))
_sym_db.RegisterMessage(DeviceBase)

DevicePhysicalEntities = _reflection.GeneratedProtocolMessageType('DevicePhysicalEntities', (_message.Message,), dict(

  Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), dict(
    DESCRIPTOR = _DEVICEPHYSICALENTITIES_ENTITY,
    __module__ = 'Device_pb2'
    # @@protoc_insertion_point(class_scope:device.DevicePhysicalEntities.Entity)
    ))
  ,
  DESCRIPTOR = _DEVICEPHYSICALENTITIES,
  __module__ = 'Device_pb2'
  # @@protoc_insertion_point(class_scope:device.DevicePhysicalEntities)
  ))
_sym_db.RegisterMessage(DevicePhysicalEntities)
_sym_db.RegisterMessage(DevicePhysicalEntities.Entity)



_DEVICESERVICE = _descriptor.ServiceDescriptor(
  name='DeviceService',
  full_name='device.DeviceService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=377,
  serialized_end=558,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetJsonDeviceBase',
    full_name='device.DeviceService.GetJsonDeviceBase',
    index=0,
    containing_service=None,
    input_type=_DEVICEBASE,
    output_type=grpc__service__pb2._GETJSONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetJsonDevicePhysicalEntities',
    full_name='device.DeviceService.GetJsonDevicePhysicalEntities',
    index=1,
    containing_service=None,
    input_type=_DEVICEPHYSICALENTITIES,
    output_type=grpc__service__pb2._GETJSONREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICESERVICE)

DESCRIPTOR.services_by_name['DeviceService'] = _DEVICESERVICE

# @@protoc_insertion_point(module_scope)
