# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_dialout.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_dialout.proto',
  package='grpc_dialout',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12grpc_dialout.proto\x12\x0cgrpc_dialout\"t\n\nDeviceInfo\x12\x14\n\x0cproducerName\x18\x01 \x02(\t\x12\x12\n\ndeviceName\x18\x02 \x02(\t\x12\x13\n\x0b\x64\x65viceModel\x18\x03 \x02(\t\x12\x14\n\x0c\x64\x65viceIpAddr\x18\x04 \x01(\t\x12\x11\n\teventType\x18\x05 \x01(\t\"F\n\tChunkInfo\x12\x11\n\ttotalSize\x18\x01 \x02(\x03\x12\x16\n\x0etotalFragments\x18\x02 \x02(\x04\x12\x0e\n\x06nodeId\x18\x03 \x02(\x04\"\x8a\x01\n\nDialoutMsg\x12+\n\tdeviceMsg\x18\x01 \x02(\x0b\x32\x18.grpc_dialout.DeviceInfo\x12\x12\n\nsensorPath\x18\x02 \x02(\t\x12\x10\n\x08jsonData\x18\x03 \x02(\t\x12)\n\x08\x63hunkMsg\x18\x04 \x01(\x0b\x32\x17.grpc_dialout.ChunkInfo\"#\n\x0f\x44ialoutResponse\x12\x10\n\x08response\x18\x01 \x02(\t2S\n\x0bGRPCDialout\x12\x44\n\x07\x44ialout\x12\x18.grpc_dialout.DialoutMsg\x1a\x1d.grpc_dialout.DialoutResponse(\x01'
)




_DEVICEINFO = _descriptor.Descriptor(
  name='DeviceInfo',
  full_name='grpc_dialout.DeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='producerName', full_name='grpc_dialout.DeviceInfo.producerName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='grpc_dialout.DeviceInfo.deviceName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceModel', full_name='grpc_dialout.DeviceInfo.deviceModel', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceIpAddr', full_name='grpc_dialout.DeviceInfo.deviceIpAddr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventType', full_name='grpc_dialout.DeviceInfo.eventType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=152,
)


_CHUNKINFO = _descriptor.Descriptor(
  name='ChunkInfo',
  full_name='grpc_dialout.ChunkInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='totalSize', full_name='grpc_dialout.ChunkInfo.totalSize', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalFragments', full_name='grpc_dialout.ChunkInfo.totalFragments', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='grpc_dialout.ChunkInfo.nodeId', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=224,
)


_DIALOUTMSG = _descriptor.Descriptor(
  name='DialoutMsg',
  full_name='grpc_dialout.DialoutMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceMsg', full_name='grpc_dialout.DialoutMsg.deviceMsg', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensorPath', full_name='grpc_dialout.DialoutMsg.sensorPath', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jsonData', full_name='grpc_dialout.DialoutMsg.jsonData', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunkMsg', full_name='grpc_dialout.DialoutMsg.chunkMsg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=365,
)


_DIALOUTRESPONSE = _descriptor.Descriptor(
  name='DialoutResponse',
  full_name='grpc_dialout.DialoutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='grpc_dialout.DialoutResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=402,
)

_DIALOUTMSG.fields_by_name['deviceMsg'].message_type = _DEVICEINFO
_DIALOUTMSG.fields_by_name['chunkMsg'].message_type = _CHUNKINFO
DESCRIPTOR.message_types_by_name['DeviceInfo'] = _DEVICEINFO
DESCRIPTOR.message_types_by_name['ChunkInfo'] = _CHUNKINFO
DESCRIPTOR.message_types_by_name['DialoutMsg'] = _DIALOUTMSG
DESCRIPTOR.message_types_by_name['DialoutResponse'] = _DIALOUTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceInfo = _reflection.GeneratedProtocolMessageType('DeviceInfo', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEINFO,
  '__module__' : 'grpc_dialout_pb2'
  # @@protoc_insertion_point(class_scope:grpc_dialout.DeviceInfo)
  })
_sym_db.RegisterMessage(DeviceInfo)

ChunkInfo = _reflection.GeneratedProtocolMessageType('ChunkInfo', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKINFO,
  '__module__' : 'grpc_dialout_pb2'
  # @@protoc_insertion_point(class_scope:grpc_dialout.ChunkInfo)
  })
_sym_db.RegisterMessage(ChunkInfo)

DialoutMsg = _reflection.GeneratedProtocolMessageType('DialoutMsg', (_message.Message,), {
  'DESCRIPTOR' : _DIALOUTMSG,
  '__module__' : 'grpc_dialout_pb2'
  # @@protoc_insertion_point(class_scope:grpc_dialout.DialoutMsg)
  })
_sym_db.RegisterMessage(DialoutMsg)

DialoutResponse = _reflection.GeneratedProtocolMessageType('DialoutResponse', (_message.Message,), {
  'DESCRIPTOR' : _DIALOUTRESPONSE,
  '__module__' : 'grpc_dialout_pb2'
  # @@protoc_insertion_point(class_scope:grpc_dialout.DialoutResponse)
  })
_sym_db.RegisterMessage(DialoutResponse)



_GRPCDIALOUT = _descriptor.ServiceDescriptor(
  name='GRPCDialout',
  full_name='grpc_dialout.GRPCDialout',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=404,
  serialized_end=487,
  methods=[
  _descriptor.MethodDescriptor(
    name='Dialout',
    full_name='grpc_dialout.GRPCDialout.Dialout',
    index=0,
    containing_service=None,
    input_type=_DIALOUTMSG,
    output_type=_DIALOUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCDIALOUT)

DESCRIPTOR.services_by_name['GRPCDialout'] = _GRPCDIALOUT

# @@protoc_insertion_point(module_scope)
