# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_service.proto',
  package='grpc_service',
  syntax='proto2',
  serialized_pb=_b('\n\x12grpc_service.proto\x12\x0cgrpc_service\"\x1e\n\x0cGetJsonReply\x12\x0e\n\x06result\x18\x01 \x02(\t\" \n\x0eSubscribeReply\x12\x0e\n\x06result\x18\x01 \x02(\t\"\x1d\n\x0b\x43onfigReply\x12\x0e\n\x06result\x18\x01 \x02(\t\"[\n\x0bReportEvent\x12\x10\n\x08token_id\x18\x01 \x02(\t\x12\x13\n\x0bstream_name\x18\x02 \x02(\t\x12\x12\n\nevent_name\x18\x03 \x02(\t\x12\x11\n\tjson_text\x18\x04 \x02(\t\"$\n\x10GetReportRequest\x12\x10\n\x08token_id\x18\x01 \x02(\t\"3\n\x0cLoginRequest\x12\x11\n\tuser_name\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"\x1e\n\nLoginReply\x12\x10\n\x08token_id\x18\x01 \x02(\t\"!\n\rLogoutRequest\x12\x10\n\x08token_id\x18\x01 \x02(\t\"\x1d\n\x0bLogoutReply\x12\x0e\n\x06result\x18\x01 \x02(\t\"\'\n\x10SubscribeRequest\x12\x13\n\x0bstream_name\x18\x01 \x02(\t2\xbc\x02\n\x0bGrpcService\x12?\n\x05Login\x12\x1a.grpc_service.LoginRequest\x1a\x18.grpc_service.LoginReply\"\x00\x12\x42\n\x06Logout\x12\x1b.grpc_service.LogoutRequest\x1a\x19.grpc_service.LogoutReply\"\x00\x12W\n\x15SubscribeByStreamName\x12\x1e.grpc_service.SubscribeRequest\x1a\x1c.grpc_service.SubscribeReply\"\x00\x12O\n\x0eGetEventReport\x12\x1e.grpc_service.GetReportRequest\x1a\x19.grpc_service.ReportEvent\"\x00\x30\x01')
)




_GETJSONREPLY = _descriptor.Descriptor(
  name='GetJsonReply',
  full_name='grpc_service.GetJsonReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc_service.GetJsonReply.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=66,
)


_SUBSCRIBEREPLY = _descriptor.Descriptor(
  name='SubscribeReply',
  full_name='grpc_service.SubscribeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc_service.SubscribeReply.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=100,
)


_CONFIGREPLY = _descriptor.Descriptor(
  name='ConfigReply',
  full_name='grpc_service.ConfigReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc_service.ConfigReply.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=131,
)


_REPORTEVENT = _descriptor.Descriptor(
  name='ReportEvent',
  full_name='grpc_service.ReportEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_id', full_name='grpc_service.ReportEvent.token_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='grpc_service.ReportEvent.stream_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_name', full_name='grpc_service.ReportEvent.event_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='json_text', full_name='grpc_service.ReportEvent.json_text', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=224,
)


_GETREPORTREQUEST = _descriptor.Descriptor(
  name='GetReportRequest',
  full_name='grpc_service.GetReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_id', full_name='grpc_service.GetReportRequest.token_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=262,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='grpc_service.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='grpc_service.LoginRequest.user_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='grpc_service.LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=315,
)


_LOGINREPLY = _descriptor.Descriptor(
  name='LoginReply',
  full_name='grpc_service.LoginReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_id', full_name='grpc_service.LoginReply.token_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=347,
)


_LOGOUTREQUEST = _descriptor.Descriptor(
  name='LogoutRequest',
  full_name='grpc_service.LogoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_id', full_name='grpc_service.LogoutRequest.token_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=382,
)


_LOGOUTREPLY = _descriptor.Descriptor(
  name='LogoutReply',
  full_name='grpc_service.LogoutReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc_service.LogoutReply.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=413,
)


_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='grpc_service.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='grpc_service.SubscribeRequest.stream_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=454,
)

DESCRIPTOR.message_types_by_name['GetJsonReply'] = _GETJSONREPLY
DESCRIPTOR.message_types_by_name['SubscribeReply'] = _SUBSCRIBEREPLY
DESCRIPTOR.message_types_by_name['ConfigReply'] = _CONFIGREPLY
DESCRIPTOR.message_types_by_name['ReportEvent'] = _REPORTEVENT
DESCRIPTOR.message_types_by_name['GetReportRequest'] = _GETREPORTREQUEST
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginReply'] = _LOGINREPLY
DESCRIPTOR.message_types_by_name['LogoutRequest'] = _LOGOUTREQUEST
DESCRIPTOR.message_types_by_name['LogoutReply'] = _LOGOUTREPLY
DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetJsonReply = _reflection.GeneratedProtocolMessageType('GetJsonReply', (_message.Message,), dict(
  DESCRIPTOR = _GETJSONREPLY,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.GetJsonReply)
  ))
_sym_db.RegisterMessage(GetJsonReply)

SubscribeReply = _reflection.GeneratedProtocolMessageType('SubscribeReply', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEREPLY,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.SubscribeReply)
  ))
_sym_db.RegisterMessage(SubscribeReply)

ConfigReply = _reflection.GeneratedProtocolMessageType('ConfigReply', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGREPLY,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.ConfigReply)
  ))
_sym_db.RegisterMessage(ConfigReply)

ReportEvent = _reflection.GeneratedProtocolMessageType('ReportEvent', (_message.Message,), dict(
  DESCRIPTOR = _REPORTEVENT,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.ReportEvent)
  ))
_sym_db.RegisterMessage(ReportEvent)

GetReportRequest = _reflection.GeneratedProtocolMessageType('GetReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETREPORTREQUEST,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.GetReportRequest)
  ))
_sym_db.RegisterMessage(GetReportRequest)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

LoginReply = _reflection.GeneratedProtocolMessageType('LoginReply', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREPLY,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.LoginReply)
  ))
_sym_db.RegisterMessage(LoginReply)

LogoutRequest = _reflection.GeneratedProtocolMessageType('LogoutRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTREQUEST,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.LogoutRequest)
  ))
_sym_db.RegisterMessage(LogoutRequest)

LogoutReply = _reflection.GeneratedProtocolMessageType('LogoutReply', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTREPLY,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.LogoutReply)
  ))
_sym_db.RegisterMessage(LogoutReply)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEREQUEST,
  __module__ = 'grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc_service.SubscribeRequest)
  ))
_sym_db.RegisterMessage(SubscribeRequest)



_GRPCSERVICE = _descriptor.ServiceDescriptor(
  name='GrpcService',
  full_name='grpc_service.GrpcService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=457,
  serialized_end=773,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='grpc_service.GrpcService.Login',
    index=0,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_LOGINREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Logout',
    full_name='grpc_service.GrpcService.Logout',
    index=1,
    containing_service=None,
    input_type=_LOGOUTREQUEST,
    output_type=_LOGOUTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeByStreamName',
    full_name='grpc_service.GrpcService.SubscribeByStreamName',
    index=2,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_SUBSCRIBEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEventReport',
    full_name='grpc_service.GrpcService.GetEventReport',
    index=3,
    containing_service=None,
    input_type=_GETREPORTREQUEST,
    output_type=_REPORTEVENT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCSERVICE)

DESCRIPTOR.services_by_name['GrpcService'] = _GRPCSERVICE

# @@protoc_insertion_point(module_scope)
