# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Ifmgr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import grpc_service_pb2 as grpc__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Ifmgr.proto',
  package='ifmgr',
  syntax='proto2',
  serialized_pb=_b('\n\x0bIfmgr.proto\x12\x05ifmgr\x1a\x12grpc_service.proto\"\xd3\x01\n\x0fIfmgrInterfaces\x12\x33\n\tinterface\x18\x01 \x03(\x0b\x32 .ifmgr.IfmgrInterfaces.Interface\x1a\x8a\x01\n\tInterface\x12\x0f\n\x07IfIndex\x18\x01 \x01(\r\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x03 \x01(\t\x12\x13\n\x0b\x41\x64minStatus\x18\x04 \x01(\r\x12\x17\n\x0fInetAddressIPV4\x18\x05 \x01(\t\x12\x1b\n\x13InetAddressIPV4Mask\x18\x06 \x01(\t\"\xeb\x01\n\x15IfmgrTypeCapabilities\x12;\n\ncapability\x18\x01 \x03(\x0b\x32\'.ifmgr.IfmgrTypeCapabilities.Capability\x1a\x94\x01\n\nCapability\x12\x11\n\tIfTypeExt\x18\x01 \x01(\r\x12\x0e\n\x06MinNum\x18\x02 \x01(\r\x12\x0e\n\x06MaxNum\x18\x03 \x01(\r\x12\x11\n\tMinSubNum\x18\x04 \x01(\r\x12\x11\n\tMaxSubNum\x18\x05 \x01(\r\x12\x14\n\x0cMaxCreateNum\x18\x06 \x01(\r\x12\x17\n\x0fMaxCreateSubNum\x18\x07 \x01(\r2\xba\x01\n\x0cIfmgrService\x12N\n\x16GetJsonIfmgrInterfaces\x12\x16.ifmgr.IfmgrInterfaces\x1a\x1a.grpc_service.GetJsonReply\"\x00\x12Z\n\x1cGetJsonIfmgrTypeCapabilities\x12\x1c.ifmgr.IfmgrTypeCapabilities\x1a\x1a.grpc_service.GetJsonReply\"\x00')
  ,
  dependencies=[grpc__service__pb2.DESCRIPTOR,])




_IFMGRINTERFACES_INTERFACE = _descriptor.Descriptor(
  name='Interface',
  full_name='ifmgr.IfmgrInterfaces.Interface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IfIndex', full_name='ifmgr.IfmgrInterfaces.Interface.IfIndex', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='ifmgr.IfmgrInterfaces.Interface.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Description', full_name='ifmgr.IfmgrInterfaces.Interface.Description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AdminStatus', full_name='ifmgr.IfmgrInterfaces.Interface.AdminStatus', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='InetAddressIPV4', full_name='ifmgr.IfmgrInterfaces.Interface.InetAddressIPV4', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='InetAddressIPV4Mask', full_name='ifmgr.IfmgrInterfaces.Interface.InetAddressIPV4Mask', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=254,
)

_IFMGRINTERFACES = _descriptor.Descriptor(
  name='IfmgrInterfaces',
  full_name='ifmgr.IfmgrInterfaces',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='ifmgr.IfmgrInterfaces.interface', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_IFMGRINTERFACES_INTERFACE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=254,
)


_IFMGRTYPECAPABILITIES_CAPABILITY = _descriptor.Descriptor(
  name='Capability',
  full_name='ifmgr.IfmgrTypeCapabilities.Capability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IfTypeExt', full_name='ifmgr.IfmgrTypeCapabilities.Capability.IfTypeExt', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MinNum', full_name='ifmgr.IfmgrTypeCapabilities.Capability.MinNum', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaxNum', full_name='ifmgr.IfmgrTypeCapabilities.Capability.MaxNum', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MinSubNum', full_name='ifmgr.IfmgrTypeCapabilities.Capability.MinSubNum', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaxSubNum', full_name='ifmgr.IfmgrTypeCapabilities.Capability.MaxSubNum', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaxCreateNum', full_name='ifmgr.IfmgrTypeCapabilities.Capability.MaxCreateNum', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaxCreateSubNum', full_name='ifmgr.IfmgrTypeCapabilities.Capability.MaxCreateSubNum', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=492,
)

_IFMGRTYPECAPABILITIES = _descriptor.Descriptor(
  name='IfmgrTypeCapabilities',
  full_name='ifmgr.IfmgrTypeCapabilities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capability', full_name='ifmgr.IfmgrTypeCapabilities.capability', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_IFMGRTYPECAPABILITIES_CAPABILITY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=492,
)

_IFMGRINTERFACES_INTERFACE.containing_type = _IFMGRINTERFACES
_IFMGRINTERFACES.fields_by_name['interface'].message_type = _IFMGRINTERFACES_INTERFACE
_IFMGRTYPECAPABILITIES_CAPABILITY.containing_type = _IFMGRTYPECAPABILITIES
_IFMGRTYPECAPABILITIES.fields_by_name['capability'].message_type = _IFMGRTYPECAPABILITIES_CAPABILITY
DESCRIPTOR.message_types_by_name['IfmgrInterfaces'] = _IFMGRINTERFACES
DESCRIPTOR.message_types_by_name['IfmgrTypeCapabilities'] = _IFMGRTYPECAPABILITIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IfmgrInterfaces = _reflection.GeneratedProtocolMessageType('IfmgrInterfaces', (_message.Message,), dict(

  Interface = _reflection.GeneratedProtocolMessageType('Interface', (_message.Message,), dict(
    DESCRIPTOR = _IFMGRINTERFACES_INTERFACE,
    __module__ = 'Ifmgr_pb2'
    # @@protoc_insertion_point(class_scope:ifmgr.IfmgrInterfaces.Interface)
    ))
  ,
  DESCRIPTOR = _IFMGRINTERFACES,
  __module__ = 'Ifmgr_pb2'
  # @@protoc_insertion_point(class_scope:ifmgr.IfmgrInterfaces)
  ))
_sym_db.RegisterMessage(IfmgrInterfaces)
_sym_db.RegisterMessage(IfmgrInterfaces.Interface)

IfmgrTypeCapabilities = _reflection.GeneratedProtocolMessageType('IfmgrTypeCapabilities', (_message.Message,), dict(

  Capability = _reflection.GeneratedProtocolMessageType('Capability', (_message.Message,), dict(
    DESCRIPTOR = _IFMGRTYPECAPABILITIES_CAPABILITY,
    __module__ = 'Ifmgr_pb2'
    # @@protoc_insertion_point(class_scope:ifmgr.IfmgrTypeCapabilities.Capability)
    ))
  ,
  DESCRIPTOR = _IFMGRTYPECAPABILITIES,
  __module__ = 'Ifmgr_pb2'
  # @@protoc_insertion_point(class_scope:ifmgr.IfmgrTypeCapabilities)
  ))
_sym_db.RegisterMessage(IfmgrTypeCapabilities)
_sym_db.RegisterMessage(IfmgrTypeCapabilities.Capability)



_IFMGRSERVICE = _descriptor.ServiceDescriptor(
  name='IfmgrService',
  full_name='ifmgr.IfmgrService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=495,
  serialized_end=681,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetJsonIfmgrInterfaces',
    full_name='ifmgr.IfmgrService.GetJsonIfmgrInterfaces',
    index=0,
    containing_service=None,
    input_type=_IFMGRINTERFACES,
    output_type=grpc__service__pb2._GETJSONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetJsonIfmgrTypeCapabilities',
    full_name='ifmgr.IfmgrService.GetJsonIfmgrTypeCapabilities',
    index=1,
    containing_service=None,
    input_type=_IFMGRTYPECAPABILITIES,
    output_type=grpc__service__pb2._GETJSONREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IFMGRSERVICE)

DESCRIPTOR.services_by_name['IfmgrService'] = _IFMGRSERVICE

# @@protoc_insertion_point(module_scope)
