# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Ifmgr_pb2 as Ifmgr__pb2
import grpc_service_pb2 as grpc__service__pb2


class IfmgrServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetJsonIfmgrInterfaces = channel.unary_unary(
        '/ifmgr.IfmgrService/GetJsonIfmgrInterfaces',
        request_serializer=Ifmgr__pb2.IfmgrInterfaces.SerializeToString,
        response_deserializer=grpc__service__pb2.GetJsonReply.FromString,
        )
    self.GetJsonIfmgrTypeCapabilities = channel.unary_unary(
        '/ifmgr.IfmgrService/GetJsonIfmgrTypeCapabilities',
        request_serializer=Ifmgr__pb2.IfmgrTypeCapabilities.SerializeToString,
        response_deserializer=grpc__service__pb2.GetJsonReply.FromString,
        )


class IfmgrServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetJsonIfmgrInterfaces(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetJsonIfmgrTypeCapabilities(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IfmgrServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetJsonIfmgrInterfaces': grpc.unary_unary_rpc_method_handler(
          servicer.GetJsonIfmgrInterfaces,
          request_deserializer=Ifmgr__pb2.IfmgrInterfaces.FromString,
          response_serializer=grpc__service__pb2.GetJsonReply.SerializeToString,
      ),
      'GetJsonIfmgrTypeCapabilities': grpc.unary_unary_rpc_method_handler(
          servicer.GetJsonIfmgrTypeCapabilities,
          request_deserializer=Ifmgr__pb2.IfmgrTypeCapabilities.FromString,
          response_serializer=grpc__service__pb2.GetJsonReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ifmgr.IfmgrService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
