# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import IPFW_pb2 as IPFW__pb2
import grpc_service_pb2 as grpc__service__pb2


class ipfw_eventServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubscribeEventStream = channel.unary_unary(
        '/ipfw_event.ipfw_eventService/SubscribeEventStream',
        request_serializer=IPFW__pb2.EventStream.SerializeToString,
        response_deserializer=grpc__service__pb2.SubscribeReply.FromString,
        )


class ipfw_eventServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SubscribeEventStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ipfw_eventServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubscribeEventStream': grpc.unary_unary_rpc_method_handler(
          servicer.SubscribeEventStream,
          request_deserializer=IPFW__pb2.EventStream.FromString,
          response_serializer=grpc__service__pb2.SubscribeReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ipfw_event.ipfw_eventService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
