# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IPFW.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import grpc_service_pb2 as grpc__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IPFW.proto',
  package='ipfw_event',
  syntax='proto2',
  serialized_pb=_b('\n\nIPFW.proto\x12\nipfw_event\x1a\x12grpc_service.proto\"\"\n\x0b\x45ventStream\x12\x13\n\x0bstream_name\x18\x01 \x01(\t2d\n\x11ipfw_eventService\x12O\n\x14SubscribeEventStream\x12\x17.ipfw_event.EventStream\x1a\x1c.grpc_service.SubscribeReply\"\x00')
  ,
  dependencies=[grpc__service__pb2.DESCRIPTOR,])




_EVENTSTREAM = _descriptor.Descriptor(
  name='EventStream',
  full_name='ipfw_event.EventStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='ipfw_event.EventStream.stream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['EventStream'] = _EVENTSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventStream = _reflection.GeneratedProtocolMessageType('EventStream', (_message.Message,), dict(
  DESCRIPTOR = _EVENTSTREAM,
  __module__ = 'IPFW_pb2'
  # @@protoc_insertion_point(class_scope:ipfw_event.EventStream)
  ))
_sym_db.RegisterMessage(EventStream)



_IPFW_EVENTSERVICE = _descriptor.ServiceDescriptor(
  name='ipfw_eventService',
  full_name='ipfw_event.ipfw_eventService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=82,
  serialized_end=182,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeEventStream',
    full_name='ipfw_event.ipfw_eventService.SubscribeEventStream',
    index=0,
    containing_service=None,
    input_type=_EVENTSTREAM,
    output_type=grpc__service__pb2._SUBSCRIBEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IPFW_EVENTSERVICE)

DESCRIPTOR.services_by_name['ipfw_eventService'] = _IPFW_EVENTSERVICE

# @@protoc_insertion_point(module_scope)
