# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import LLDP_pb2 as LLDP__pb2
import grpc_service_pb2 as grpc__service__pb2


class LLDPServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubscribeNeighborEvent = channel.unary_unary(
        '/lldp.LLDPService/SubscribeNeighborEvent',
        request_serializer=LLDP__pb2.NeighborEvent.SerializeToString,
        response_deserializer=grpc__service__pb2.SubscribeReply.FromString,
        )
    self.SubscribeEventStream = channel.unary_unary(
        '/lldp.LLDPService/SubscribeEventStream',
        request_serializer=LLDP__pb2.EventStream.SerializeToString,
        response_deserializer=grpc__service__pb2.SubscribeReply.FromString,
        )


class LLDPServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SubscribeNeighborEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeEventStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LLDPServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubscribeNeighborEvent': grpc.unary_unary_rpc_method_handler(
          servicer.SubscribeNeighborEvent,
          request_deserializer=LLDP__pb2.NeighborEvent.FromString,
          response_serializer=grpc__service__pb2.SubscribeReply.SerializeToString,
      ),
      'SubscribeEventStream': grpc.unary_unary_rpc_method_handler(
          servicer.SubscribeEventStream,
          request_deserializer=LLDP__pb2.EventStream.FromString,
          response_serializer=grpc__service__pb2.SubscribeReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'lldp.LLDPService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
