# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LLDP.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import grpc_service_pb2 as grpc__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LLDP.proto',
  package='lldp',
  syntax='proto2',
  serialized_pb=_b('\n\nLLDP.proto\x12\x04lldp\x1a\x12grpc_service.proto\"\xb6\x01\n\rNeighborEvent\x12.\n\x08neighbor\x18\x01 \x03(\x0b\x32\x1c.lldp.NeighborEvent.Neighbor\x1au\n\x08Neighbor\x12\x0e\n\x06IfName\x18\x01 \x01(\t\x12\x0f\n\x07\x41gentID\x18\x02 \x01(\r\x12\x19\n\x11NeighborChassisId\x18\x03 \x01(\t\x12\x16\n\x0eNeighborPortId\x18\x04 \x01(\t\x12\x15\n\rNeighborevent\x18\x05 \x01(\r\"\"\n\x0b\x45ventStream\x12\x13\n\x0bstream_name\x18\x01 \x01(\t2\xa7\x01\n\x0bLLDPService\x12M\n\x16SubscribeNeighborEvent\x12\x13.lldp.NeighborEvent\x1a\x1c.grpc_service.SubscribeReply\"\x00\x12I\n\x14SubscribeEventStream\x12\x11.lldp.EventStream\x1a\x1c.grpc_service.SubscribeReply\"\x00')
  ,
  dependencies=[grpc__service__pb2.DESCRIPTOR,])




_NEIGHBOREVENT_NEIGHBOR = _descriptor.Descriptor(
  name='Neighbor',
  full_name='lldp.NeighborEvent.Neighbor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IfName', full_name='lldp.NeighborEvent.Neighbor.IfName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AgentID', full_name='lldp.NeighborEvent.Neighbor.AgentID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NeighborChassisId', full_name='lldp.NeighborEvent.Neighbor.NeighborChassisId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NeighborPortId', full_name='lldp.NeighborEvent.Neighbor.NeighborPortId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Neighborevent', full_name='lldp.NeighborEvent.Neighbor.Neighborevent', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=223,
)

_NEIGHBOREVENT = _descriptor.Descriptor(
  name='NeighborEvent',
  full_name='lldp.NeighborEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neighbor', full_name='lldp.NeighborEvent.neighbor', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NEIGHBOREVENT_NEIGHBOR, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=223,
)


_EVENTSTREAM = _descriptor.Descriptor(
  name='EventStream',
  full_name='lldp.EventStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='lldp.EventStream.stream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=259,
)

_NEIGHBOREVENT_NEIGHBOR.containing_type = _NEIGHBOREVENT
_NEIGHBOREVENT.fields_by_name['neighbor'].message_type = _NEIGHBOREVENT_NEIGHBOR
DESCRIPTOR.message_types_by_name['NeighborEvent'] = _NEIGHBOREVENT
DESCRIPTOR.message_types_by_name['EventStream'] = _EVENTSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NeighborEvent = _reflection.GeneratedProtocolMessageType('NeighborEvent', (_message.Message,), dict(

  Neighbor = _reflection.GeneratedProtocolMessageType('Neighbor', (_message.Message,), dict(
    DESCRIPTOR = _NEIGHBOREVENT_NEIGHBOR,
    __module__ = 'LLDP_pb2'
    # @@protoc_insertion_point(class_scope:lldp.NeighborEvent.Neighbor)
    ))
  ,
  DESCRIPTOR = _NEIGHBOREVENT,
  __module__ = 'LLDP_pb2'
  # @@protoc_insertion_point(class_scope:lldp.NeighborEvent)
  ))
_sym_db.RegisterMessage(NeighborEvent)
_sym_db.RegisterMessage(NeighborEvent.Neighbor)

EventStream = _reflection.GeneratedProtocolMessageType('EventStream', (_message.Message,), dict(
  DESCRIPTOR = _EVENTSTREAM,
  __module__ = 'LLDP_pb2'
  # @@protoc_insertion_point(class_scope:lldp.EventStream)
  ))
_sym_db.RegisterMessage(EventStream)



_LLDPSERVICE = _descriptor.ServiceDescriptor(
  name='LLDPService',
  full_name='lldp.LLDPService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=262,
  serialized_end=429,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeNeighborEvent',
    full_name='lldp.LLDPService.SubscribeNeighborEvent',
    index=0,
    containing_service=None,
    input_type=_NEIGHBOREVENT,
    output_type=grpc__service__pb2._SUBSCRIBEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeEventStream',
    full_name='lldp.LLDPService.SubscribeEventStream',
    index=1,
    containing_service=None,
    input_type=_EVENTSTREAM,
    output_type=grpc__service__pb2._SUBSCRIBEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LLDPSERVICE)

DESCRIPTOR.services_by_name['LLDPService'] = _LLDPSERVICE

# @@protoc_insertion_point(module_scope)
