# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Syslog_pb2 as Syslog__pb2
import grpc_service_pb2 as grpc__service__pb2


class SyslogServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubscribeLOGEvent = channel.unary_unary(
        '/sys_log.SyslogService/SubscribeLOGEvent',
        request_serializer=Syslog__pb2.LOGEvent.SerializeToString,
        response_deserializer=grpc__service__pb2.SubscribeReply.FromString,
        )
    self.SubscribeEventStream = channel.unary_unary(
        '/sys_log.SyslogService/SubscribeEventStream',
        request_serializer=Syslog__pb2.EventStream.SerializeToString,
        response_deserializer=grpc__service__pb2.SubscribeReply.FromString,
        )


class SyslogServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SubscribeLOGEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeEventStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SyslogServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubscribeLOGEvent': grpc.unary_unary_rpc_method_handler(
          servicer.SubscribeLOGEvent,
          request_deserializer=Syslog__pb2.LOGEvent.FromString,
          response_serializer=grpc__service__pb2.SubscribeReply.SerializeToString,
      ),
      'SubscribeEventStream': grpc.unary_unary_rpc_method_handler(
          servicer.SubscribeEventStream,
          request_deserializer=Syslog__pb2.EventStream.FromString,
          response_serializer=grpc__service__pb2.SubscribeReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sys_log.SyslogService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
