# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Syslog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import grpc_service_pb2 as grpc__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Syslog.proto',
  package='sys_log',
  syntax='proto2',
  serialized_pb=_b('\n\x0cSyslog.proto\x12\x07sys_log\x1a\x12grpc_service.proto\"u\n\x08LOGEvent\x12\"\n\x03log\x18\x01 \x03(\x0b\x32\x15.sys_log.LOGEvent.LOG\x1a\x45\n\x03LOG\x12\r\n\x05Group\x18\x01 \x01(\t\x12\x0c\n\x04\x43ode\x18\x02 \x01(\t\x12\x10\n\x08Severity\x18\x03 \x01(\r\x12\x0f\n\x07\x43ontent\x18\x04 \x01(\t\"\"\n\x0b\x45ventStream\x12\x13\n\x0bstream_name\x18\x01 \x01(\t2\xa5\x01\n\rSyslogService\x12\x46\n\x11SubscribeLOGEvent\x12\x11.sys_log.LOGEvent\x1a\x1c.grpc_service.SubscribeReply\"\x00\x12L\n\x14SubscribeEventStream\x12\x14.sys_log.EventStream\x1a\x1c.grpc_service.SubscribeReply\"\x00')
  ,
  dependencies=[grpc__service__pb2.DESCRIPTOR,])




_LOGEVENT_LOG = _descriptor.Descriptor(
  name='LOG',
  full_name='sys_log.LOGEvent.LOG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Group', full_name='sys_log.LOGEvent.LOG.Group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Code', full_name='sys_log.LOGEvent.LOG.Code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Severity', full_name='sys_log.LOGEvent.LOG.Severity', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='sys_log.LOGEvent.LOG.Content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=162,
)

_LOGEVENT = _descriptor.Descriptor(
  name='LOGEvent',
  full_name='sys_log.LOGEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='sys_log.LOGEvent.log', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LOGEVENT_LOG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=162,
)


_EVENTSTREAM = _descriptor.Descriptor(
  name='EventStream',
  full_name='sys_log.EventStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='sys_log.EventStream.stream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=198,
)

_LOGEVENT_LOG.containing_type = _LOGEVENT
_LOGEVENT.fields_by_name['log'].message_type = _LOGEVENT_LOG
DESCRIPTOR.message_types_by_name['LOGEvent'] = _LOGEVENT
DESCRIPTOR.message_types_by_name['EventStream'] = _EVENTSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LOGEvent = _reflection.GeneratedProtocolMessageType('LOGEvent', (_message.Message,), dict(

  LOG = _reflection.GeneratedProtocolMessageType('LOG', (_message.Message,), dict(
    DESCRIPTOR = _LOGEVENT_LOG,
    __module__ = 'Syslog_pb2'
    # @@protoc_insertion_point(class_scope:sys_log.LOGEvent.LOG)
    ))
  ,
  DESCRIPTOR = _LOGEVENT,
  __module__ = 'Syslog_pb2'
  # @@protoc_insertion_point(class_scope:sys_log.LOGEvent)
  ))
_sym_db.RegisterMessage(LOGEvent)
_sym_db.RegisterMessage(LOGEvent.LOG)

EventStream = _reflection.GeneratedProtocolMessageType('EventStream', (_message.Message,), dict(
  DESCRIPTOR = _EVENTSTREAM,
  __module__ = 'Syslog_pb2'
  # @@protoc_insertion_point(class_scope:sys_log.EventStream)
  ))
_sym_db.RegisterMessage(EventStream)



_SYSLOGSERVICE = _descriptor.ServiceDescriptor(
  name='SyslogService',
  full_name='sys_log.SyslogService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=201,
  serialized_end=366,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeLOGEvent',
    full_name='sys_log.SyslogService.SubscribeLOGEvent',
    index=0,
    containing_service=None,
    input_type=_LOGEVENT,
    output_type=grpc__service__pb2._SUBSCRIBEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeEventStream',
    full_name='sys_log.SyslogService.SubscribeEventStream',
    index=1,
    containing_service=None,
    input_type=_EVENTSTREAM,
    output_type=grpc__service__pb2._SUBSCRIBEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYSLOGSERVICE)

DESCRIPTOR.services_by_name['SyslogService'] = _SYSLOGSERVICE

# @@protoc_insertion_point(module_scope)
